name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Compile the code
      run: |
        ./mvnw compile
          
    - name: Run the tests
      run: |
        ./mvnw test
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag spring-pet-clinic:$(date +%s)

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      env:  
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
    
    - name: Publish Docker image to JFrog Artifactory
      run: |
        jf rt docker image push spring-pet-clinic petclinic-docker:latest  
        
